### ISSUE TITLE
VG RDF shell script does not support all vg.JSON possibilities

### ISSUE THREAD

**Issue by JervenBolleman** [ekg/vg#110]
The jq script depends on all types of nodes being present. e.g. it fails on some of the test data json files when a path element in the JSON tree is missing.

**Comment by ekg** [comment]
Do you have an example of this?

**Comment by JervenBolleman** [comment]
from the test directory cyclic/all.json, mises a path element in the JSON tree. This is not supported by the conversion script.

**Comment by JervenBolleman** [comment]
This will be fixed with pull requests #171 #170
