### ISSUE TITLE
node arrows help legibility in dot output

### ISSUE THREAD

**Issue by ekg** [ekg/vg#125]
@glennhickey @adamnovak : we discussed this and I've tested removing edge arrows, but the result is something like this:

![image](https://cloud.githubusercontent.com/assets/145425/10561367/9bab628e-74f3-11e5-98a7-bbe3687a9821.png)

I find it difficult to tell what is going on with nodes 5 and 21. That said, it's clear after a moment's consideration that 5 reverses into 21.

**Comment by glennhickey** [comment]
I'm still in the arrow-free camp, but you look at these things way more
often!  Maybe an option to toggle?

**Comment by ekg** [comment]
I think I'm settling into arrow-free. It is easy enough to add a switch
later if my eyes start bleeding.

**Comment by adamnovak** [comment]
I think the real problem here is that the edges don't need to have any arc
to them. Maybe you can force them to arc a bit somehow?

**Comment by ekg** [comment]
Either I'm going to be digging upstream in graphviz or we will need to
support or implement a viewer suitable to the task of some of these graphs.
