### ISSUE TITLE
add vg validate command

### ISSUE THREAD

**Issue by glennhickey** [ekg/vg#126]
As we continue to develop, tools are being made that sometimes create erroneous vg files which can lead to hard-to-figure-out errors in the other tools that read them.  It would help both users and developers to have "vg validate" that can be used to verify if an input file is valid.  The most common types of errors I'm seeing are within paths, where for example contiguous path segments are not connected by any edge.  Same thing can happen in gams...

**Comment by ekg** [comment]
Agreed. The paths are one thing. Also, including edges that refer to non-existent nodes (and nodes with no edges) might be worthy of errors or warnings. Do you mean validating the JSON and/or protobuf?

**Comment by glennhickey** [comment]
Yeah, non-existant nodes is definitely another one!  I think disconnected
graphs / orphan nodes is definitely at least a warning too.

For your question, I think operating on protubuf is simplest and most
useful.  To be clear, I'm not worried about problems with the protobuf
itself as I imagine the google parser already checks for that.

**Comment by ekg** [comment]
> I'm not worried about problems with the protobuf itself as I imagine the google parser already checks for that.

Fair enough. I'll restrict the first implementation to the things we discussed.

**Comment by ekg** [comment]
Ask and you shall receive.

**Comment by glennhickey** [comment]
Awesome, thanks!
