### ISSUE TITLE
Simulated data with SVs crashes vg

### ISSUE THREAD

**Issue by edawson** [ekg/vg#129]
I have a toy test case I built to test vg's variant calling chops. I'm not sure if it's me or vg but I never get past indexing without getting a seg fault. The test case I'm using is available at [here](https://bitbucket.org/dawsonet/vg-test-data/src/5421c2207aeed82babd53511c6ca71b7ccc9428e?at=master). It has 50 deletions (each 100bp in length) randomly inserted in chr22 using RSVSim. I've tried to describe the errors / details in the READMEs in each directory of the repo.

**Comment by ekg** [comment]
We looked at this yesterday. Some things came up that aren't made clear in the documentation.

1. When using vg construct to go from VCF+FASTA to a graph, vg will only consider REF/ALT pairs that are 100% A/T/G/C DNA sequences. So, the SV standard of writing "N" as the REF and "<DEL>" as the ALT won't work.

2. Building vg is really a pain and weird bugs will arise if your build isn't perfect. I'm going to see what I can do to make it easier, probably biicodization.

**Comment by edawson** [comment]
Yep! Additionally:
   1. VG throws a std::out_of_range error if the vcc file hasn't been compressed with bgzip. Catching the exception with a more informative message might be helpful.
   2. I've added a mod_vcf.py script to the above repo that will reformat deletions in VCFs to bring them more in line with what VG wants. Specifically, it makes the REF the CONSENSUS sequence of the called deletion and the ALT an empty string. It also has the option to insert a random base as the ALT (which I'll change to the first base of the deletion at some point I think).
   3. What platform are you building on? I'm going to keep chipping away at a docker build, as even those aren't passing all tests for me yet.

**Comment by ekg** [comment]
I build on ubuntu 15.04 for development, and also on whatever the sanger is running on its compute farm. Builds also work on travis, although it isn't happy that I require sudo to set up the build process. Again, biicode may help, although I will need to biicode-ize a lot of stuff to move all the submodules of vg there. It's not a certain thing that it resolves all the build problems, but cmake at least provides the tooling to configure things correctly depending on system.
