### ISSUE TITLE
Broken mapping lengths

### ISSUE THREAD

**Issue by ekg** [ekg/vg#136]

**Comment by ekg** [comment]
```shell
➜  test git:(master) ✗ vg msga -f msgas/s.fa -k 16 -b s1 -B 20 -M 2 | vg view -
H       HVN:Z:1.0
S       1       TCAGATTCTCATCCCTCCTCAAGGGCTTCT
P       1       s1      1       +       15M
P       1       s2      1       +       15M
L       1       +       5       +       0M
L       1       +       2       +       0M
S       2       AACTACTCCACATCAAAGCTAC
P       2       s1      2       +       5M
L       2       +       3       +       0M
S       3       CCAGGCCATTTTAAGTTTCCTG
P       3       s1      3       +       3M
L       3       +       4       +       0M
S       4       T
P       4       s1      4       +       1M
L       4       +       5       +       0M
S       5       GGACTAAGGACAAAGGTGCGGGGAG
P       5       s1      5       +       10M
P       5       s2      2       +       5M
➜  test git:(master) ✗ echo -n TCAGATTCTCATCCCTCCTCAAGGGCTTCT | wc -c
30
```

Note that mapping `P       1       s1      1       +       15M` says that the first node is 15 long, but in this case a full-length mapping should be 30.

I think this must be related to the merging of the alignment bands.

**Comment by glennhickey** [comment]
This seems related to the errors I'm seeing in paths coming from vg mgsa.  PR #141 changes vg validate to catch these cases.

**Comment by glennhickey** [comment]
Just to add a more concrete example from our end:

data:  http://hgwdev.sdsc.edu/~anovak/hgvm/hgvm.tar.gz
command:  vg msga -k 32 -m 32 -B 640 -D -f hgvm/BRCA1/ref.fa -f hgvm/BRCA1/GI262359905.fa -f hgvm/BRCA1/GI528476558.fa >BRCA1.vg

vg validate BRCA1.vg gives:

graph path 'GI528476558' invalid (reverse) mapping at rank 61: offset (31) != edit length (21) -1

**Comment by ekg** [comment]
I think this is (mostly) resolved due to resolution of some mapping merging issues.

```
vg msga -f BRCA1.fa -b ref -B 640 -m 32 -k 32 -K 16 -X 2 -t 3 -D >BRCA1.vg
vg validate BRCA1.vg       # passes
```

Validation throws up these warnings:
```
[vg] warning: node ID 0 is not allowed. Skipping.
[vg] warning: node ID 0 is not allowed. Skipping.
[vg] warning: node ID 0 is not allowed. Skipping.
```

I'm not sure what's causing it. MSGA is doing something silly. It does seem that the problems with node size are resolved.

That all said I have some other tests involving reversing paths that still aren't going well. There is the assumption in vg normalize that the normalized graph will be perfectly-mappable by the banded mapping, which isn't necessarily true.

**Comment by ekg** [comment]
Oh, and this fix also resolves the example at the start of this issue:

```bash
➜  test git:(master) ✗ vg msga -f msgas/s.fa -k 16 -b s1 -B 20 -M 2 | vg view - 
[vg] warning: node ID 0 is not allowed. Skipping.
[vg] warning: node ID 0 is not allowed. Skipping.
H       HVN:Z:1.0
S       1       TCAGATTCTCATCCCTCCTCAAGGGCTTCT
P       1       s1      1       +       30M
P       1       s2      1       +       30M
L       1       +       5       +       0M
L       1       +       2       +       0M
S       2       AACTACTCCACATCAAAGCTAC
P       2       s1      2       +       22M
L       2       +       3       +       0M
S       3       CCAGGCCATTTTAAGTTTCCTG
P       3       s1      3       +       22M
L       3       +       4       +       0M
S       4       T
P       4       s1      4       +       1M
L       4       +       5       +       0M
S       5       GGACTAAGGACAAAGGTGCGGGGAG
P       5       s1      5       +       25M
P       5       s2      2       +       25M
```
