### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by ekg** [ekg/vg#142]
Suggestions? Here's what I've got:

![screenshot from 2015-11-03 12 37 51](https://cloud.githubusercontent.com/assets/145425/10908413/c2d15e2a-8229-11e5-9b99-a6cae48b38a3.png)

**Comment by ekg** [comment]
```
vg view -d cyclic/self_loops.vg | sed 's%1:GATTACA%vg%' | sed s%penwidth=2,%penwidth=2,fontsize=32% | dot2browser
```

**Comment by ekg** [comment]
Looking good?

**Comment by adamnovak** [comment]
It might be nice to open it up with an SVG editor and manually tweak it a bit. Some of the nobbly curves could be less nobbly, and the corners of the ends of the edges don't need to be visible.

Also, do you like the serif font? I think sans is in this year.

Here's one where it sort of looks like a spinny thing:

[VG Logo Attempt.pdf](https://github.com/ekg/vg/files/31141/VG.Logo.Attempt.pdf)

On an unrelated note, my dot is putting little non-heads at the ends of the edges, where the lines unexpectedly get thinner.

@macieksmuga is a logos expert, so he probably has an opinion too.

**Comment by ekg** [comment]
I would even add the reverse complement "normal" edge to the logo.

The font is much nicer sans. That way future anthropologists will be able
to use it for dating lithographic structures deposited above and below.

**Comment by macieksmuga** [comment]
I'm working on some potential logo sketches right now. Hope you don't mind that I'm exploring a couple of different concepts in addition to the one presented here.

**Comment by macieksmuga** [comment]
Here's a very quick sketch based on the current design. Font is Futura, because the lowercase "g" in all other sans serifs looks plain goofy by itself.
![vg0](https://cloud.githubusercontent.com/assets/6685511/11073961/dcfb31d6-87a1-11e5-9e93-e28c02a832a3.png)

**Comment by macieksmuga** [comment]
Here's a slight variant, with the extra edges rotated around. Looks a bit more balanced to me.
![vg1](https://cloud.githubusercontent.com/assets/6685511/11074537/fa6ca9fe-87a4-11e5-845f-4ef903fddc80.png)

**Comment by ryan-williams** [comment]
I love these @macieksmuga! 

Total drive-by nits, for whatever they're worth:
* the tiny edge jutting from the left side of the lower-right node is bothering me, I feel like it's uncannily small and should maybe be lengthened or omitted?
* the bottom of the "v" feels too close to the bottom edge / the letters feel like they have appropriate padding above but not below.

Thanks!

**Comment by ekg** [comment]
I love these. They're beautiful.

I like the graph with three of the four edges a little more because I think
it is cool if all the types of edges are represented. Well, the last one is
hinted at by the g....

So what does it look like with all four edge types?

**Comment by macieksmuga** [comment]
Ok, here's another quick one. I added the fourth edge type, removed that awkward little bit of path at the lower right, and adjusted the spacing of the letters. I couldn't do much about the proximity of the "v" to the bottom edge - as I was trying to maintain the bottom of the "g" curve aligned with the bottom of the box (and stretching the letters didn't work wonders either).
![vg2](https://cloud.githubusercontent.com/assets/6685511/11076646/b5bcd98a-87b0-11e5-8ec7-ef36f1dca62b.png)

**Comment by ekg** [comment]
@macieksmuga I like this one!

Anyone else with a :+1: ?

**Comment by ekg** [comment]
@macieksmuga do you have a vectorized version? We can slap it into the readme!

**Comment by macieksmuga** [comment]
[vg_logo.pdf](https://github.com/ekg/vg/files/36391/vg_logo.pdf)

**Comment by ekg** [comment]
I'll say this is resolved for now. The only thing missing is color and/or emoji :grinning:
