### ISSUE TITLE
alignment does traverse reversing edges

### ISSUE THREAD

**Issue by ekg** [ekg/vg#143]
## GSSW prep is too reductive

I think this is a known problem to others, but I'm just remembering it and thinking about how to handle it. Here's a basic example graph:

![screenshot from 2015-11-04 10 14 10](https://cloud.githubusercontent.com/assets/145425/10935255/d2724052-82dc-11e5-9fad-40cdd0ac2912.png)

```js
{"node": [{"sequence": "CAAATAAGGCTTGGAAATTTT", "id": 1}, {"sequence": "CTGG", "id": 2}, {"sequence": "AGTTC", "id": 3}, {"sequence": "GACCCCCG", "id": 4}, {"sequence": "TATTATATTCCAACTCTCTG", "id": 5}], "edge": [{"from": 1, "to": 2}, {"from": 4, "to": 1, "to_end": true}, {"from": 2, "to": 3}, {"from": 3, "to": 5}, {"from_start": true, "from": 5, "to": 4}]}
```

When made ready for alignment, it looks like:

![screenshot from 2015-11-04 10 15 25](https://cloud.githubusercontent.com/assets/145425/10935284/fb86e15a-82dc-11e5-9003-7fe1cc48be19.png)

```js
{"node": [{"sequence": "N", "id": 6}, {"sequence": "CAAATAAGGCTTGGAAATTTT", "id": 1}, {"sequence": "CTGG", "id": 2}, {"sequence": "AGTTC", "id": 3}, {"sequence": "GACCCCCG", "id": 4}, {"sequence": "TATTATATTCCAACTCTCTG", "id": 5}], "edge": [{"from": 6, "to": 1}, {"from": 1, "to": 2}, {"from": 2, "to": 3}, {"from": 3, "to": 5}, {"from": 6, "to": 4}]}
```

Too much information is lost in the preparation for GSSW to correctly obtain an alignment here.

## Example

This has consequences for `vg msga`. We might edit this graph:

![image](https://cloud.githubusercontent.com/assets/145425/10937183/0c5f6856-82e9-11e5-83a2-3dec0c068591.png)

```js
{"node": [{"sequence": "CAAATAAGGCTTGGAAATTTTCTGG", "id": 1}, {"sequence": "AGTTCTATTATATTCCAACTCTCTG", "id": 2}], "edge": [{"from": 1, "to": 2}]}
```

With this alignment:

![screenshot from 2015-11-04 11 44 35](https://cloud.githubusercontent.com/assets/145425/10937247/711cf47a-82e9-11e5-8b65-ef1d68f6270a.png)

```js
{"sequence": "CAGAGAGTTGGAATATAATAGACCCCCGAAAATTTCCAAGCCTTATTTG", "path": {"mapping": [{"position": {"node_id": 2, "offset": 24}, "edit": [{"from_length": 20, "to_length": 20}, {"to_length": 8, "sequence": "GACCCCCG"}], "is_reverse": true, "rank": 1}, {"position": {"node_id": 1, "offset": 20}, "edit": [{"from_length": 21, "to_length": 21}], "is_reverse": true, "rank": 2}]}}
```

Yielding the graph which I mentioned above.

We can't properly align to it due to the modification of the graph that's used for GSSW alignment:

![screenshot from 2015-11-04 11 38 46](https://cloud.githubusercontent.com/assets/145425/10937106/b4594406-82e8-11e5-9277-37d4710e20a9.png)

```js
{"node": [{"sequence": "CAAATAAGGCTTGGAAATTTT", "id": 1}, {"sequence": "CTGG", "id": 2}, {"sequence": "AGTTC", "id": 3}, {"sequence": "GACCCCCG", "id": 4}, {"sequence": "TATTATATTCCAACTCTCTG", "id": 5}], "edge": [{"from": 1, "to": 2}, {"from": 4, "to": 1, "to_end": true}, {"from": 2, "to": 3}, {"from": 3, "to": 5}, {"from_start": true, "from": 5, "to": 4}]}
```
```js
{"sequence": "CAGAGAGTTGGAATATAATAGACCCCCGAAAATTTCCAAGCCTTATTTG", "path": {"mapping": [{"position": {"node_id": 5, "offset": 19}, "edit": [{"from_length": 20, "to_length": 20}, {"to_length": 8, "sequence": "GACCCCCG"}], "is_reverse": true, "rank": 1}, {"position": {"node_id": 1, "offset": 20}, "edit": [{"from_length": 21, "to_length": 21}], "is_reverse": true, "rank": 2}]}}
```

One consequence of this is that we sometimes fail to annotate paths that have been use to generate the graph. This could cause some of the problems that @glennhickey has seen with vg graphs for the ga4gh construction bakeoff.

**Comment by ekg** [comment]
To reproduce.

Make the graph:

```bash
echo '{"node": [{"sequence": "CAAATAAGGCTTGGAAATTTT", "id": 1}, {"sequence": "CTGG", "id": 2}, {"sequence": "AGTTC", "id": 3}, {"sequence": "GACCCCCG", "id": 4}, {"sequence": "TATTATATTCCAACTCTCTG", "id": 5}], "edge": [{"from": 1, "to": 2}, {"from": 4, "to": 1, "to_end": true}, {"from": 2, "to": 3}, {"from": 3, "to": 5}, {"from_start": true, "from": 5, "to": 4}]}' \
    | vg view -Jv - >f.vg
```

Index it

```
vg index f.vg -x f.xg -g f.gcsa -k 16
```

And align with the same bandwidth as the test case:

```
vg view -dA <(vg map -s CAGAGAGTTGGAATATAATAGACCCCCGAAAATTTCCAAGCCTTATTTG -B 16 -x f.xg -g f.gcsa -k 20 ) f.vg | dot2browser
```

Here's the result:

![screenshot from 2015-11-04 18 06 25](https://cloud.githubusercontent.com/assets/145425/10947236/c97c8d30-831e-11e5-97a3-8e7199d9451e.png)

This clearly should align, but it won't due to the breakage of the graph. Now I have a target test for resolution.

**Comment by ekg** [comment]
OK! It is not a problem with the reorientation of the nodes in a forward direction. Case:

```
vg mod -f f.vg >f1.vg
vg index f1.vg -x f1.xg -g f1.gcsa -k 16
vg view -dA <(vg map -s CAGAGAGTTGGAATATAATAGACCCCCGAAAATTTCCAAGCCTTATTTG -B 16 -x f1.xg -g f1.gcsa -k 20 ) f1.vg | dot2browser 
```

![screenshot from 2015-11-04 18 27 15](https://cloud.githubusercontent.com/assets/145425/10947783/ebe29e20-8321-11e5-9072-1351b4754af4.png)

So that looks fine. It looks like there is a problem with query step in the mapper where it does not traverse the reversed edges.

**Comment by ekg** [comment]
Getting there. The biggest problem was a missed "rebuild_indexes" after an xg context expansion!

![screenshot from 2015-11-09 08 50 37](https://cloud.githubusercontent.com/assets/145425/11029455/f7bcc77a-86be-11e5-9567-d478f22a979e.png)

Remaining issues: alignment is_reverse masking (described in comments in #127), and included paths should probably break up the nodes so that they perfectly map to whole nodes. For instance, in this example path "q" might start halfway through the last node, but this can't be represented cleanly in the reference graph such as indexed in xg.

**Comment by adamnovak** [comment]
I was looking at this when fixing up the handling of some of the BRCA1 paths (which go through backward). They don't actually use partial nodes, but even with no edits you can still use the right part (or the left part if going in reverse) of a node just by putting a not-at-one-end offset on your edit-free mapping, right?

It's still a little clunky, though. It might make sense to restrict these sorts of reference paths so that they have to start and end at node boundaries. Among other things, it would mean you wouldn't have to worry about if you should really have one or two new mappings when splitting a node.

**Comment by ekg** [comment]
Supporting path inclusion when the paths don't perfectly match the graph seems like an important feature if we are going to use paths to provide isomorphism between graphs. Otherwise we'll need to cut up nodes in the graph to match the new path.

**Comment by ekg** [comment]
The original problem mentioned in this is related to not rebuilding the indexes in VG after extending the graph with the xg index. I have a fix handy locally that I need to push up.

As an aside, we should be passing in some functions to xg add nodes and add edges to the graph, so that internally it doesn't need to rebuild the indexes of the graph structure. This would also clean up the interface.
