### ISSUE TITLE
K-mers input to GCSA: kmer, node+position, previous characters, successive characters

### ISSUE THREAD

**Issue by ryan-williams** [ekg/vg#15]

**Comment by ekg** [comment]
Updated title. `vg` should produce an output stream that can be used by [GCSA2](https://github.com/jltsiren/gcsa2) as input. The format (as @jltsiren and I have discussed) should look like:

```text
label, starting_position, previous_chars, successive_chars, successive_positions
```

Where positions in the graph are given as `(node_id, offset)` pairs. A label is a kmer. The previous characters are the characters immediately prior to the position in the graph--- for instance there might be only one if the position is in the middle of a node, or many if it is at the beginning and there are multiple inbound edges. The successive characters are those immediately after the kmer, and as with previous there can be several if there are several outbound edges. The same applies to the successive positions.
