### ISSUE TITLE
self-cycling nodes lose their self-cycles during divide_node

### ISSUE THREAD

**Issue by ekg** [ekg/vg#178]
If I have this FASTA file (saved as `l.fa`):

```text
>a1                                                                   
TCAGATTCTCATCCCTCCTCAAGGGCTTCTGGACTAAGGACAAAGGTGCGGGGAG               
>a2                                                                   
TCAGATTCTCATCCCTCCTCAAGGGCTTCTGGACTAAGGGCTTCTGGACTAAGGACAAAGGTGCGGGGAG
```

I can assemble it using `vg msga`:

```bash
vg msga -f l.fa -k 8 -b a1 -B 8 | vg view -dpn - ...
```

![screenshot from 2015-12-15 16 32 07](https://cloud.githubusercontent.com/assets/145425/11827445/87d69c7c-a349-11e5-9075-b80bf18794c2.png)

And that's fine. However, if I break the nodes into a smaller length during construction, so that there would be several nodes inside the cycle, things get screwy:

```bash
vg msga -f msgas/l.fa -k 8 -b a1 -B 8 -m 8 | vg validate -
graph path 'a2' invalid: edge from 7 end to 5 start does not exist             
[vg msga] failed to include alignment, retrying                                
...
```

In a possibly-related issue, chop (`vg mod -X`) is also messing up the cycle:

```bash
vg msga -f l.fa -k 8 -b a1 -B 8 | vg mod -X 8 | vg view -dpn - ...
```

![screenshot from 2015-12-15 16 36 04](https://cloud.githubusercontent.com/assets/145425/11827524/f37599d8-a349-11e5-8838-bce048d6a3b6.png)

The cycle is lost and the graph becomes invalid because the path traverses a nonexistent edge.

**Comment by ekg** [comment]
The problem seems to stem from the [way we are storing edges in vg](https://github.com/ekg/vg/blob/ba4f3af892c20d4a56b9309c7592367d4e018add/src/vg.hpp#L202-L205).

```c++
    // edges by sides of nodes they connect
    // Since duplicate edges are not permitted, two edges cannot connect the same pair of node sides.
    // Each edge is indexed here with the smaller NodeSide first. The actual node order is recorded in the Edge object.
    pair_hash_map<pair<NodeSide, NodeSide>, Edge*> edge_by_sides;
```

**Comment by adamnovak** [comment]
The data structure is supposed to allow multiple edges between the same nodes, as long as they don't connect the same pair of sides. So you can have an edge from the left side of node 1 to the right side of node 2, and an edge from the left side of node 2 to the right side of node 1 (or even the left side of node 1) together in the same graph with no problems. The only thing you aren't supposed to be able to do is have an edge from the left side of node 1 to the right side of node 2, and another, duplicate edge connecting the same two sides (for example, an edge from the right side of node 2 to the left side of node 1).

It doesn't look to me like you would try to create such duplicate edges under any segmentation of that top graph.

**Comment by ekg** [comment]
@adamnovak cool, makes sense. I've messed up something else.

**Comment by ekg** [comment]
The underlying problem is in [VG::divide_node](https://github.com/ekg/vg/blob/ba4f3af892c20d4a56b9309c7592367d4e018add/src/vg.cpp#L3017-L3043), which does not adjust edges that are linking from the node into itself when dividing it into two separate nodes. Sorry for the noise!

**Comment by ekg** [comment]
Yup, that was the problem.

![screenshot from 2015-12-15 18 14 21](https://cloud.githubusercontent.com/assets/145425/11829154/b2e96d78-a357-11e5-9cef-04f03ccc90d3.png)
