### ISSUE TITLE
Error pulling fs layer b2ae0a712b39 on DockerFile

### ISSUE THREAD

**Issue by willgdjones** [ekg/vg#181]
I'm running into an issue in building the docker container from the Docker file.

Seems like an issue with the b2ae0a712b39 image layer on docker.io/library/ubuntu.

Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
fcee8bcfe180: Pulling fs layer
4cdc0cbc1936: Pulling fs layer
d9e545b90db8: Pulling fs layer
c4bea91afef3: Pulling fs layer
Pulling repository docker.io/library/ubuntu
af88597ec24b: Error pulling image (14.04) from docker.io/library/ubuntu, Server error: Status 0 while fetching image layer (b2ae0a712b396bf106bd301a41bbff642bd6dfa861596092ac34513b36425241) 1a41bbff642bd6dfa861596092ac34513b36425241)
b2ae0a712b39: Error pulling dependent layers
Error pulling image (14.04) from docker.io/library/ubuntu, Server error: Status 0 while fetching image layer (b2ae0a712b396bf106bd301a41bbff642bd6dfa861596092ac34513b36425241)

Docker version 1.9.0

**Comment by edawson** [comment]
Hey Will, I'm debugging this right now. I'll push a fresh container to [my docker hub repo](https://hub.docker.com/r/erictdawson/vg_docker/) as soon as I can and post back here. I'll update the dockerfile as well.

**Comment by willgdjones** [comment]
Hey Eric - retrying recently has just succeeded... it must have been the image layer resource was temporarily unavailable for some strange reason.
