### ISSUE TITLE
Not all GAM fields present in JSON output

### ISSUE THREAD

**Issue by edawson** [ekg/vg#187]
I've been working on a Python solution to filter and [call variants in GAM output](https://github.com/edawson/ggsv/blob/master/python/ggsv.py). I've run into an issue that has me stumped on how to proceed. When outputting GAM as JSON it seems many of the fields are dropped:
1. Any empty/0 fields are not included, even as placeholders. For example, if the `from_length` of an edit is 0, there is no `from_length` key in the JSON output.
2. There are no qualities or scores in the JSON output. In fact only the "sequence" and "path" fields of the alignment are output.

If this is by design it might be good to document it. If it isn't we should find a way to ensure all fields are pushed out when we go GAM -> JSON.

**Comment by ekg** [comment]
The omission of 0-valued fields seems reasonable to me and should be
semantically correct in all cases. The second part is confusing. Are you
sure that the quality field is filled out in the GAM you are working with?

**Comment by edawson** [comment]
I agree that omission of 0-valued fields is semantically correct. It makes parsing a bit harder, but I guess has the added benefit of taking up significantly less space.

I'm not at all sure the quality field is filled out in my GAM. Shouldn't the read qualities be included, or have I managed to confuse myself again?

**Comment by ekg** [comment]
Try to print out the quality field from within C++. If it is there but not
converted we have a problem.

**Comment by edawson** [comment]
Indeed, the quality fields of the GAM alignments are empty as well, so it's by design and not by mistake that this is the case.
