### ISSUE TITLE
VG::distance_to_tail can't work, breaks softclips

### ISSUE THREAD

**Issue by adamnovak** [ekg/vg#192]
While investigating some bad mappings in the graph bake-off, I noticed that end softclip handling wasn't always running when it should be. I think I traced the problem to an error in converting some functions to support oriented nodes.

Softclip handling depends on [VG::distance_to_tail](https://github.com/ekg/vg/blob/master/src/vg.cpp#L6755-L6773), which is supposed to tell you how far your node is from the tail of the graph. If a read dangles off a node that isn't anywhere near the tail of the graph, softclip handling shouldn't happen there.

It looks like the function is trying to take an arbitrary edge from the node given, towards the edge of the graph, and when it gets to a tail or hits its limit in bases, it will stop. However, it's calling [VG::sides_from](https://github.com/ekg/vg/blob/master/src/vg.cpp#L422-L433) on a node ID, and that function is now only defined on a NodeSide. There's a constructor to build a NodeSide from a node ID, which implicitly creates the start side of the node. So we're looking for edges off the start side of this node, when I think the function means to be looking for edges off the end side of the node.

Really, the function ought to take in an oriented node (NodeTraversal) and keep going right to abritrary nodes with next_nodes(). If we can guarantee we only use the function on ordered and oriented alignment graphs, though, it might be possible to keep it as is and just use the correct side.

The other problem with the function is that if it hits its length limit exactly, but hasn't reached the end, it will return the length limit instead of the special -1 value. The limit is easy to hit right now if you have a length-1 node last, because it will look for a place to go, not find one (since it's looking off the start instead of the end), and visit the same node again.

The final problem is that if it does return its -1 value, [I think the softclip code will take -1 as meaning the tail is closer than the ending softclip distance](https://github.com/ekg/vg/blob/master/src/mapper.cpp#L1148) and run the softclip code anyway.

**Comment by adamnovak** [comment]
It doesn't help that the [reported distances to tails](https://github.com/ekg/vg/blob/master/src/mapper.cpp#L1152) are actually calculated with the distance_to_head function, unlike the ones actually used for decision-making.

**Comment by ekg** [comment]
Looks bad. Sorry about this. I guess it proves that it's not done until
it's tested.

**Comment by ekg** [comment]
I can take this on as soon as I finish unroll, which should be soon. In the
meantime patches are welcome.

**Comment by ekg** [comment]
I'm going to guess that this is a large part of the problem with alignment against graphs. Perhaps related to https://github.com/ekg/vg/issues/173.

@adamnovak have you hacked on this, or should I dig in?

**Comment by adamnovak** [comment]
I haven't tried to fix this at all yet; for the bake-off I think we're
going to try just throwing out the read alignments that look obviously like
bad soft clips, and eat the hit to variant calling power.

-Adam

**Comment by ekg** [comment]
It sounds reasonably easy to fix. We might be seeing an artifact of it
elsewhere. I'll look into it today.
