### ISSUE TITLE
paired-end reads

### ISSUE THREAD

**Issue by davebiffuk** [ekg/vg#2]
Is there any way to keep the separation distance of paired-end reads or is that information lost in graph format?

**Comment by ekg** [comment]
There is no standard method to do so encoded in the existing schema or command line interface, but I think it would be trivial to encode this as all that is needed is the coordinates (node id and position) of the mapped mate.

An alternative approach that I think is more conceptually simple would be to encode the read pair as a single read with a big gap in the middle. Which is what it effectively is... The problem would be when read pairs map to very distant regions. This is already an issue for BAM/SAM.

Perhaps the solution of recording the coordinates of the other alignment is the simplest one.
