### ISSUE TITLE
Travis is not happy - should I wait?

### ISSUE THREAD

**Issue by pgrosu** [ekg/vg#36]
Hi Erik,

Below is a link to the Travis report:

https://travis-ci.org/ekg/vg

I assume you already know about this.  Should I wait for a fix?

Thanks,
~p

**Comment by ekg** [comment]
Solution: type make twice. The build is failing but it is fine on my system
apart from this. A dependency in the Makefile is broken.

**Comment by pgrosu** [comment]
Sounds good - thanks for the quick reply :)  I'll close the issue.

**Comment by ekg** [comment]
@pgrosu by the way, I fixed the issue. protobuf 3 seems to need gcc 4.9.

**Comment by pgrosu** [comment]
@ekg thank you :)
