### ISSUE TITLE
Steps to compile vg locally without needing sudo access

### ISSUE THREAD

**Issue by pgrosu** [ekg/vg#37]
Hi Erik,

I wrote up the following steps, in case anyone would like to install `vg` without needing sudo access.  Feel free to change/integrate them any way you prefer :)  Below are the steps:

1) Download and install `jansson` in your home directory, and please replace `YOUR_USERNAME` with your username on the system:

```
git clone https://github.com/akheron/jansson
autoreconf -i
./configure --prefix=/home/YOUR_USERNAME/apps/jansson
make
make install
cd ..
```

2) Download `vg` and enter its directory:

```
git clone --recursive https://github.com/ekg/vg.git
cd vg
```
3) Update `INCLUDES` and `LDFLAGS` in `Makefile`:

Add to `INCLUDES` the following, with `YOUR_USERNAME` being set appropriately:

```
-I/home/YOUR_USERNAME/apps/jansson/include
```

Add to `LDFLAGS` the following, with `YOUR_USERNAME` being set appropriately:

```
-L/home/YOUR_USERNAME/apps/jansson/lib
```

They should look something like this, with  `YOUR_USERNAME` being set appropriately:

```
INCLUDES=-I./ -I/home/YOUR_USERNAME/apps/jansson/include -Icpp -I$(VCFLIB)/src -I$(VCFLIB) -Ifastahack -Igssw/src -Iprotobuf/build/include -Irocksdb/include -Iprogress_bar -Isparsehash/build/include -Ilru_cache -Ihtslib -Isha1
LDFLAGS=-L./ -L/home/YOUR_USERNAME/apps/jansson/lib -Lvcflib -Lgssw/src -Lprotobuf -Lsnappy -Lrocksdb -Lprogressbar -Lhtslib -lvcflib -lgssw -lprotobuf -lhts -lpthread -ljansson -lncurses -lrocksdb -lsnappy -lz -lbz2
```

4) Next compile `vg`:
```
make
```
5) For the final step, just update your `LD_LIBRARY_PATH` with `jansson`, and add it to you `.bashrc` file to keep it persistent between sessions.  Just as before, `YOUR_USERNAME` would need to be replaced with your specific username on the system:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/YOUR_USERNAME/apps/jansson/lib
```
Hope it helps others as well,
Paul

**Comment by ekg** [comment]
@pgrosu Very interesting, and thanks for the writeup. I try to avoid setting additional things in the ld search path. When programs are mature and distributed via package managers I think it makes sense to share libraries, but for applications like this one the ideal is to have a fully self-contained binary.

We could encapsulate jansson in the build, but it's only used for JSON output from protobuf using pbjson, which is going away as soon as JSON support is default in protobuf 3: https://github.com/google/protobuf/issues/350

**Comment by pgrosu** [comment]
@ekg No problem, that makes sense - sorry for the noise.  I'll close the issue, and if people need something like this, then they can search for it here.

Thank you for the link about protobuf 3 going to provide support for JSON, which can simplify some things.  Either way, if the the compilation could be streamlined from just cloning the git repository, that would make it easier, but probably not a high-priority.

Thank you for making this great program!
Paul

**Comment by ekg** [comment]
FYI, at present you can use make get-deps on ubuntu/debian to get the
dependencies. I'm not sure if mac OSX builds have worked yet.

**Comment by pgrosu** [comment]
That's a very useful feature, but I think I need `sudo` access for it based on the following line, which I don't always have on all systems:

https://github.com/ekg/vg/blob/master/Makefile#L20

Still a very nice feature to have in the Makefile for self-installing the required packages.  I have not tried it on a Mac yet.

**Comment by ekg** [comment]
Yes, you're right that you need sudo! vg hasn't quite grown up, but it's
getting closer. I think I'll hold on the jansson issue for the moment
though.

**Comment by pgrosu** [comment]
It's no problem - to me it feels complete and fairly mature :)  There's always a way to make things run, so I'm not too worried.  It was just another way to reach autonomy :)
