### ISSUE TITLE
GFA output is not really GFA

### ISSUE THREAD

**Issue by ekg** [ekg/vg#60]
It's come to my attention that vg is not outputting correct GFA format.

That said, it's not clear yet to me if GFA can support vg graphs as @adamnovak 's recent commits enable, as such graphs have four kinds of edges.

Any suggestions about how to deal with this would be welcome. I think GFA is a useful format as it enables text processing of graphs on the command line.

**Comment by adamnovak** [comment]
GFA can express bidirected graphs, you just have to convert them to the
labeled-ends format. Edges that come to a node's start connect to the label
for its start, and edges that come to a node's end connect to the label for
its end.

**Comment by ekg** [comment]
I went through a period of confusion that's just ended thanks to the half
draft of the specification. Just need to resolve this in vg...
