### ISSUE TITLE
Extracting a valid subgraph with vg find

### ISSUE THREAD

**Issue by mlin** [ekg/vg#80]
Probably a novice roadbump: I have `11.vg` for the whole chromosome and I'd like to extract a subgraph and then align a sequence to it. Based on [05_vg_find.t#L32](https://github.com/ekg/vg/blob/faa5e9fa2994a695f589ff790d3488aee62230b6/test/t/05_vg_find.t#L32) I'm trying this:

```
$ vg find -p 11:1910000-1970000 -c 256 vg/11.vg -d vg/index > 11_1910000_1970000.vg
$ vg view 11_1910000_1970000.vg -g | wc -l
graph invalid: edge index=12754 (174413169->174413171) cannot find node (from) 174413169
[vg view] warning: graph is invalid!
28866
$ vg align -s GTCCCAGCACCCAGTGCGCATGGTTGGGGGTGGTGGAGACCAAGAGGGTCCTGAGCCTCTCCTCATGCCCTGAGCTGACCTGAGCCCCCAGGCTGGATCCAGCCTGAGGCCGCTCGGCCCAGCTGTGGGCTCAATCACTGCCAGGCCCAGGACAGGAGCAGCTGACACAGCACTTGGGAACTGAGCTGCTCCAGCCCTAGGTAGCTGCCTCCCCACATGCCTAGTGCTTCTGATTTTGCAGTTTCATTGACTCGTTCTGCAGATATGATGGGTGTCTTCTCTGTGGCTGGCCTAGGGGCTTGTAGCAAGGGTCACAGGGTGTCTGGTGGCTGCTCTGGCAGGCAGGACAGAGGCTAGGGGCTTCATCTGCCATCCCTGGCCAGGGGCCTCTTAGGCTGCAGGCCTTTTGAGCCTCCTGACCTCCGCATTGGGCATGGCCTGACCTCCAGGTTTCCAGGAGCAGGGGCATGGGGTTGCTGTGGCCGTGGACGGGAGGCTGCATCAGAAACACAGCAGGGCTGTGGCTGGGTAGAGCTCAGAGGGACAGGCCCTGGGTCCTTGTTCTCGAGGCTGAGCCGAGGGGTGCAGATGATCTGACAAGGGGCCAGGGCTGGTCGGGGGCGGGGTGGGCAGTGGCTGCCTCCTCAGCACTGCTGACCCCAACTACCCCCTGCCCCTGGTGCTGTCCACTCTGCACCCCAGTGCTGAGTGCCCAACTGTGGCCTTTGGGCCTGCCTCTCGGCTGCCCTTGGTCACCGTCCCAAGCGGATCAGGTGGGAAACAAGGGAGTGCTGTCACTGGGTGGTTCCCCAGCTGGGGAGGGTGGCCTGGATCCTCTCTCAGTGGCTGGGGCATCTGAGAAAGGATGGGGGCACGTCACCTCCCTTGTGTGGGTGGTGGCTCTGTCGAGGTTTTGCTTTTCTGAACTGTGTGTATTCATGAGGCAAGCAGGGTTTGACATGAAGCCTTCAGAAAATAGTGGCTGTGAGGACCCAAGGGAATGGCAAAGTGAAGTCCAGAACATCAGAGTCTGGGGTGCTGCTCCTCGAAGGGACTTCCCAGACGCTGAAGGCTGCAGGGCTGAGTGTCAGGGCCCAGTGCAAGACCTGGGAGAGGAGGGACAGGAGGGAGGGTGTCCCCAGGCTGTCTGCTATTTCACACAGTTGTCCATTCATCCACCCATCTATTCATTCCCATGCATTCACTCTCACCTTCACCACTTCCTTTCCTTCCTTCCTCCCTCCTTCTCTTCCATCATCCATCCCTCCGTCTGTCCATCCTTTCAACCACCCATACAATCACCTACCCATCCACTCATCCCTCCATTTCATCTATCCCTCCCGCCATCCATCCATCCATCCATCATTAGTCTATCCATCCATTCATCCACCCACCTATCCATCTATCTACCCATCCATCTACCTGTCTATCCATCCATCCATCCATCTCTTCATCTATCCATCTACCCATTCATGCATCCATCCATCCCTCCCTCCCTCCCTTCATCCACCCTCCCTTCATCCATCCATCCCTCCCTCCATCCATCCATCCACACATCCACTCATCCATCCATCCACCCACCCACCTACCCATCCACTCATTCATCCCTTCCTCCATCCATCCTTCCCGCTCTCTGTCCATCCATTCATCTATCCCTTCACCCATCCATCCACCCACCCATCTACCCATCCACTCATCCATCTCTCCATTCATCCATCCACCTATCCATTCACTCACTCACCTATCTATCTATCCGTCCTTTCATCCATCCTTTCATCTACCCATCCACACATCCATCCCTCCATTCATCCATCCACCTATCCATCCATCCACCTGTCCATCCACTCTCATCCATCCCTTCATCCATCTATCCATCTACCCATCCATGCATCCATCCCTTCATTCATCAATCCCTCCATTATCTATCTATCCATCCATCCAACCACCTACCCATCCCTTCATTTATCGCTCCTTCCATCCATCCCTCCACCCACCCACCTACCCATTCACTCACTCATCCCTCCTTCCATCCCCCCTCTCTCCCTCTGTCCATTCATCCAGCCATCCCTTCATCCATCCATCCACTCATCTACCTATCCACTCATGCATCCCTCCTTTCATCCATCCACCTATCCATTCACTAACCCATCCATCCATCCATCCAGCCAGCCAGCCAGCCAGCCAGCCATCCTCCCACCCACCCATCCATTCACCCACCTATTCACCCACTCATCCATCCATTAGTCCATCCATCCACCCACCTGCTTACCCATTCACTCATCCATACATCCCTCTATCCATTCATCCATCCCCTATTCATCCACTCACCCATCCCTCCACTCACCCACCCAACCATTCATCCACTCACCCACCTACCCATCCATTCA 11_1910000_1970000.vg
terminate called after throwing an instance of 'std::runtime_error'
  what():  No node 174414275 in graph
Aborted
```

(This would segfault before one of @adamnovak's recent bugfixes)

Would I be right in guessing that the subgraph I extracted using `vg find` has some sort of dangling edges to nodes in `11.vg` that were not included in the extracted subgraph? Is there an easy way to trim them off so that the result of `vg find` is a "valid" graph? If not would this be a reasonable capability to attempt adding?

(The particular sequence is the unitig from the [fermikit tests](https://github.com/lh3/fermikit/blob/master/test/test.sh))

**Comment by ekg** [comment]
Try using `vg mod -o` to remove "orphan edges".

Could you post the graph you get from `vg find`?

**Comment by adamnovak** [comment]
Yeah, it looks like your subgraph includes some edges but not the nodes on
their far ends, which breaks the assumption that most of the code makes
that edges always go to actual nodes. Running the subgraph through `vg mod
-o` as Erik recommends ought to fix it up.

We might want to make `vg find` remove these "orphan" edges before
outputting the graph. Is there a use case for being able to pull out a
graph with orphan edges if none of the other tools can use it?

-Adam

**Comment by mlin** [comment]
YES! Thanks guys! `vg mod -o` is what I was looking for exactly. I support `vg find` having an option, or even the default, to apply this transformation. I have a couple long flights coming up, will try to hack on this to get my feet wet.

I am now approaching nirvana. To elaborate, here is the illustration of how the fermikit unitigs align to the reference in this region (cc @lh3):

<img src="https://github.com/dnanexus-rnd/vg/wiki/mlin/HS1011_unitigs.png"/>

I'm working with the one with the nice long "deletion" in the middle. It spans one of the breakpoints in a complex rearrangement discussed in Fig. 7 of [English et al. (2015)](http://www.biomedcentral.com/1471-2164/16/286).

My procedure is:

```
vg find -p 11:1910000-1940000 -c 64 vg/11.vg -d vg/index > 11_1910000_1940000.vg
vg mod -o 11_1910000_1940000.vg > 11_1910000_1940000.mod.vg
vg align -s TGAATGGATGGGTAGGTGGGTGAGTGGATGAATGGTTGGGTGGGTGAGTGGAGGGATGGGTGAGTGGATGAATAGGGGATGGATGAATGGATAGAGGGATGTATGGATGAGTGAATGGGTAAGCAGGTGGGTGGATGGATGGACTAATGGATGGATGAGTGGGTGAATAGGTGGGTGAATGGATGGGTGGGTGGGAGGATGGCTGGCTGGCTGGCTGGCTGGCTGGATGGATGGATGGATGGGTTAGTGAATGGATAGGTGGATGGATGAAAGGAGGGATGCATGAGTGGATAGGTAGATGAGTGGATGGATGGATGAAGGGATGGCTGGATGAATGGACAGAGGGAGAGAGGGGGGATGGAAGGAGGGATGAGTGAGTGAATGGGTAGGTGGGTGGGTGGAGGGATGGATGGAAGGAGCGATAAATGAAGGGATGGGTAGGTGGTTGGATGGATGGATAGATAGATAATGGAGGGATTGATGAATGAAGGGATGGATGCATGGATGGGTAGATGGATAGATGGATGAAGGGATGGATGAGAGTGGATGGACAGGTGGATGGATGGATAGGTGGATGGATGAATGGAGGGATGGATGTGTGGATGGGTAGATGAAAGGATGGATGAAAGGACGGATAGATAGATAGGTGAGTGAGTGAATGGATAGGTGGATGGATGAATGGAGAGATGGATGAGTGGATGGGTAGATGGGTGGGTGGATGGATGGGTGAAGGGATAGATGAATGGATGGACAGAGAGCGGGAAGGATGGATGGAGGAAGGGATGAATGAGTGGATGGGTAGGTGGGTGGGTGGATGGATGGATGAGTGGATGTGTGGATGGATGGATGGAGGGAGGGATGGATGGATGAAGGGAGGGTGGATGAAGGGAGGGAGGGAGGGATGGATGGATGCATGAATGGGTAGATGGATAGATGAAGAGATGGATGGATGGATGGATAGACAGGTAGATGGATGGGTAGATAGATGGATAGGTGGGTGGATGAATGGATGGATAGACTAATGATGGATGGATGGATGGATGGCGGGAGGGATAGATGAAATGGAGGGATGAGTGGATGGGTAGGTGATTGTATGGGTGGTTGAAAGGATGGACAGACGGAGGGATGGATGATGGAAGAGAAGGAGGGAGGAAGGAAGGAAAGGAAGTGGTGAAGGTGAGAGTGAATGCATGGGAATGAATAGATGGGTGGATGAATGGACAACTGTGTGAAATAGCAGACAGCCTGGGGACACCCTCCCTCCTGTCCCTCCTCTCCCAGGTCTTGCACTGGGCCCTGACACTCAGCCCTGCAGCCTTCAGCGTCTGGGAAGTCCCTTCGAGGAGCAGCACCCCAGACTCTGATGTTCTGGACTTCACTTTGCCATTCCCTTGGGTCCTCACAGCCACTATTTTCTGAAGGCTTCATGTCAAACCCTGCTTGCCTCATGAATACACACAGTTCAGAAAAGCAAAACCTCGACAGAGCCACCACCCACACAAGGGAGGTGACGTGCCCCCATCCTTTCTCAGATGCCCCAGCCACTGAGAGAGGATCCAGGCCACCCTCCCCAGCTGGGGAACCACCCAGTGACAGCACTCCCTTGTTTCCCACCTGATCCGCTTGGGACGGTGACCAAGGGCAGCCGAGAGGCAGGCCCAAAGGCCACAGTTGGGCACTCAGCACTGGGGTGCAGAGTGGACAGCACCAGGGGCAGGGGGTAGTTGGGGTCAGCAGTGCTGAGGAGGCAGCCACTGCCCACCCCGCCCCCGACCAGCCCTGGCCCCTTGTCAGATCATCTGCACCCCTCGGCTCAGCCTCGAGAACAAGGACCCAGGGCCTGTCCCTCTGAGCTCTACCCAGCCACAGCCCTGCTGTGTTTCTGATGCAGCCTCCCGTCCACGGCCACAGCAACCCCATGCCCCTGCTCCTGGAAACCTGGAGGTCAGGCCATGCCCAATGCGGAGGTCAGGAGGCTCAAAAGGCCTGCAGCCTAAGAGGCCCCTGGCCAGGGATGGCAGATGAAGCCCCTAGCCTCTGTCCTGCCTGCCAGAGCAGCCACCAGACACCCTGTGACCCTTGCTACAAGCCCCTAGGCCAGCCACAGAGAAGACACCCATCATATCTGCAGAACGAGTCAATGAAACTGCAAAATCAGAAGCACTAGGCATGTGGGGAGGCAGCTACCTAGGGCTGGAGCAGCTCAGTTCCCAAGTGCTGTGTCAGCTGCTCCTGTCCTGGGCCTGGCAGTGATTGAGCCCACAGCTGGGCCGAGCGGCCTCAGGCTGGATCCAGCCTGGGGGCTCAGGTCAGCTCAGGGCATGAGGAGAGGCTCAGGACCCTCTTGGTCTCCACCACCCCCAACCATGCGCACTGGGTGCTGGGAC 11_1910000_1940000.mod.vg > HS1011_breakpoint.gam
vg view -d 11_1910000_1940000.mod.vg -A HS1011_breakpoint.gam > 11_1910000_1940000_HS1011.dot
neato 11_1910000_1940000_HS1011.dot -Tsvg -O # using neato because dot segfaults
```

(I've reverse-complemented the sequence compared to the original post above. I realized the hard way that `vg align` runs only the forward strand, which is fine.)

[Here is the SVG](https://dl.dnanex.us/F/D/kFZ0zZy0bV1zXV3gbzQXBy2y55VJJG9Z5fP1FYxx/11_1910000_1940000_HS1011.dot.svg). I can see it in Firefox while my other SVG viewers crash. It has a weird U-shape due to using neato instead of dot. The alignment action is roughly 90% to the right and 60% from the top.

The result with `vg align` is that the longer, downstream region is aligned nicely while the upstream region is forced into a crappy alignment immediately 5' of that. With `vg map -B 10000`, the downstream region is aligned nicely with the upstream region soft-clipped. (`vg map` crashes without `-B` as in #54.)

This leaves me with the following things to explore next -- suggestions welcome:

1. Inject a new edge into `11_1910000_1940000.mod.vg` corresponding to BLAT's "intron" and see if the unitig will `vg align` to that.
1. See if there's a gap extension penalty I can change in order to get `vg align` to find it itself.
2. Would the banded alignment, if fixed, somehow recover this in the desired way.

**Comment by mlin** [comment]
Closing this issue in favor of PR #81

**Comment by ekg** [comment]
In response to the alignment result, the problem is that the aligner is banded and so it can't handle long deletions.

I think there might be a very simple algorithm for handling really long deletions. Basically we need to look for alignments of the soft-clipping regions of the unitigs in a region up to some N kp around. If we find alignments in the right places, then we record the split and realign against a graph which includes an approximation of the deletion based on the observed split size. If this graph maintains our original graph's ids (it should no problem) then mappings against it are still valid mappings against the original graph + some large deletion, so it will be straightforward to convert it back to a mapping including the deletion on the original graph.

It's also interesting to think about how to deal with long insertions. Where these are wholly captured in a single, small unitig, it will be possible to detect them using standard alignment. However, when they get big enough, this will become costly and we'll need to use an approach that looks similar to that we use for deletions. We'd start with bands on the ends of the unitig, walking inward until we stop mapping. We can use the limits of the mapping to estimate the insertion allele from the unitig, drop that into the graph (taking care to minimally-disrupt it), then fine-tune the graph with the banded alignment of the unitig.

**Comment by ekg** [comment]
@mlin Would you please send me the input to the SVG you linked above? I'd like to test recent changes and see how they go.

**Comment by mlin** [comment]
@ekg here's the graph:

https://dl.dnanex.us/F/D/8Yy6Q8f60YKB9K6bYy4Pk65K7qB60BVZ0K7JJf5b/11_1910000_1940000.vg

and a version in which I've manually injected an edge corresponding to the breakpoint:

https://dl.dnanex.us/F/D/P9f74Fg4bK9k2v56fZbvFKQqFjBk85z3Xkzb0ppp/11_1910000_1940000.inject.vg

and the sequence again:

```
vg align -s TGAATGGATGGGTAGGTGGGTGAGTGGATGAATGGTTGGGTGGGTGAGTGGAGGGATGGGTGAGTGGATGAATAGGGGATGGATGAATGGATAGAGGGATGTATGGATGAGTGAATGGGTAAGCAGGTGGGTGGATGGATGGACTAATGGATGGATGAGTGGGTGAATAGGTGGGTGAATGGATGGGTGGGTGGGAGGATGGCTGGCTGGCTGGCTGGCTGGCTGGATGGATGGATGGATGGGTTAGTGAATGGATAGGTGGATGGATGAAAGGAGGGATGCATGAGTGGATAGGTAGATGAGTGGATGGATGGATGAAGGGATGGCTGGATGAATGGACAGAGGGAGAGAGGGGGGATGGAAGGAGGGATGAGTGAGTGAATGGGTAGGTGGGTGGGTGGAGGGATGGATGGAAGGAGCGATAAATGAAGGGATGGGTAGGTGGTTGGATGGATGGATAGATAGATAATGGAGGGATTGATGAATGAAGGGATGGATGCATGGATGGGTAGATGGATAGATGGATGAAGGGATGGATGAGAGTGGATGGACAGGTGGATGGATGGATAGGTGGATGGATGAATGGAGGGATGGATGTGTGGATGGGTAGATGAAAGGATGGATGAAAGGACGGATAGATAGATAGGTGAGTGAGTGAATGGATAGGTGGATGGATGAATGGAGAGATGGATGAGTGGATGGGTAGATGGGTGGGTGGATGGATGGGTGAAGGGATAGATGAATGGATGGACAGAGAGCGGGAAGGATGGATGGAGGAAGGGATGAATGAGTGGATGGGTAGGTGGGTGGGTGGATGGATGGATGAGTGGATGTGTGGATGGATGGATGGAGGGAGGGATGGATGGATGAAGGGAGGGTGGATGAAGGGAGGGAGGGAGGGATGGATGGATGCATGAATGGGTAGATGGATAGATGAAGAGATGGATGGATGGATGGATAGACAGGTAGATGGATGGGTAGATAGATGGATAGGTGGGTGGATGAATGGATGGATAGACTAATGATGGATGGATGGATGGATGGCGGGAGGGATAGATGAAATGGAGGGATGAGTGGATGGGTAGGTGATTGTATGGGTGGTTGAAAGGATGGACAGACGGAGGGATGGATGATGGAAGAGAAGGAGGGAGGAAGGAAGGAAAGGAAGTGGTGAAGGTGAGAGTGAATGCATGGGAATGAATAGATGGGTGGATGAATGGACAACTGTGTGAAATAGCAGACAGCCTGGGGACACCCTCCCTCCTGTCCCTCCTCTCCCAGGTCTTGCACTGGGCCCTGACACTCAGCCCTGCAGCCTTCAGCGTCTGGGAAGTCCCTTCGAGGAGCAGCACCCCAGACTCTGATGTTCTGGACTTCACTTTGCCATTCCCTTGGGTCCTCACAGCCACTATTTTCTGAAGGCTTCATGTCAAACCCTGCTTGCCTCATGAATACACACAGTTCAGAAAAGCAAAACCTCGACAGAGCCACCACCCACACAAGGGAGGTGACGTGCCCCCATCCTTTCTCAGATGCCCCAGCCACTGAGAGAGGATCCAGGCCACCCTCCCCAGCTGGGGAACCACCCAGTGACAGCACTCCCTTGTTTCCCACCTGATCCGCTTGGGACGGTGACCAAGGGCAGCCGAGAGGCAGGCCCAAAGGCCACAGTTGGGCACTCAGCACTGGGGTGCAGAGTGGACAGCACCAGGGGCAGGGGGTAGTTGGGGTCAGCAGTGCTGAGGAGGCAGCCACTGCCCACCCCGCCCCCGACCAGCCCTGGCCCCTTGTCAGATCATCTGCACCCCTCGGCTCAGCCTCGAGAACAAGGACCCAGGGCCTGTCCCTCTGAGCTCTACCCAGCCACAGCCCTGCTGTGTTTCTGATGCAGCCTCCCGTCCACGGCCACAGCAACCCCATGCCCCTGCTCCTGGAAACCTGGAGGTCAGGCCATGCCCAATGCGGAGGTCAGGAGGCTCAAAAGGCCTGCAGCCTAAGAGGCCCCTGGCCAGGGATGGCAGATGAAGCCCCTAGCCTCTGTCCTGCCTGCCAGAGCAGCCACCAGACACCCTGTGACCCTTGCTACAAGCCCCTAGGCCAGCCACAGAGAAGACACCCATCATATCTGCAGAACGAGTCAATGAAACTGCAAAATCAGAAGCACTAGGCATGTGGGGAGGCAGCTACCTAGGGCTGGAGCAGCTCAGTTCCCAAGTGCTGTGTCAGCTGCTCCTGTCCTGGGCCTGGCAGTGATTGAGCCCACAGCTGGGCCGAGCGGCCTCAGGCTGGATCCAGCCTGGGGGCTCAGGTCAGCTCAGGGCATGAGGAGAGGCTCAGGACCCTCTTGGTCTCCACCACCCCCAACCATGCGCACTGGGTGCTGGGAC 11_1910000_1940000.vg > HS1011_breakpoint.gam
```
