### ISSUE TITLE
Construct a variation graph from several fasta sequences

### ISSUE THREAD

**Issue by joseale2310** [ekg/vg#91]
Hi!
I have similar genome references that I want to merge in a variation graph and then align my reads to this unique variation graph. Is this possible? That I understand is that it needs a VCF file with the variants and the reference genome to construct the graph. 

Another way could be to construct different graphs without the VCF file and then use the join function, but I am not sure if this would work!

Thanks!

**Comment by ekg** [comment]
The documentation is out of date. You can use `vg msga` to generate a
variation graph from multiple FASTA sequences. *However* part of the reason
that I have not updated the documentation is that this approach is
currently limited to sequences of up to 100kb or so due to memory
constraints.

I'm working on a solution now, but it will take a bit more time. Check back
in a week.

**Comment by joseale2310** [comment]
Hi! That makes more sense. I will try again in a week! Thank you very much.

**Comment by ekg** [comment]
How large are the sequences you want to use to build the graph?

**Comment by joseale2310** [comment]
2 Mb. And then I want to align to some reads that I have.

**Comment by ekg** [comment]
Yeah this will take a few days to complete.

**Comment by joseale2310** [comment]
No problem! Just keep up the good work. I am very excited to work with this.

**Comment by joseale2310** [comment]
Hi! How is the developping going?

**Comment by ekg** [comment]
Almost done with prep. The last few commits have enabled progressive
construction of a graph and in-memory indexing, which is crucial for
mapping reads against larger graphs efficiently. I'm going to test
something today!

**Comment by joseale2310** [comment]
Thanks! I will wait a little bit more :+1:

**Comment by ekg** [comment]
I won't push (yet) as things are somewhat broken, but I've gotten most of the way to a working MSGA implementation supporting larger graphs. I can use the indexing features in-memory and the mapper to progressively build the graph, which allows efficient alignment even against huge graphs. Will update.

**Comment by ekg** [comment]
I've implemented GCSA/xg -based multi-sequence/graph alignment, which _should_ allow us to start building graphs from big FASTA inputs. See https://github.com/ekg/vg/blob/master/test/t/16_vg_msga.t#L11 for example usage.

I haven't yet tested this on larger sequences. I have a 5MB test region from the GA4GH data working group graph bakeoffs that I need to build, so I'll start with that. Let me know how you progress, and if you run into anything weird.

There are a number of improvements to the algorithm that may be important for making larger graphs from FASTA inputs. I expect to be exploring these in the coming days.

**Comment by joseale2310** [comment]
Thanks! I guess that I need to clone and install again, right? Thank you very much. I will try also with shorter reference genome sequences that I got recently. Thanks!

**Comment by ekg** [comment]
It is still slightly broken (path inclusion seems to not be working in
msga). Debugging now. I can make a binary release when things stabilize. If
you want to start testing, I'd say go for it. I am always curious to know
if people have trouble building it. If you can use smaller tests at first
and use vg view to see what is going on.
